version: '3'
services:
  wordpress:
    #image: wordpress
    build:
        context: ./src
        dockerfile: Dockerfile
    environment:
      WORDPRESS_DB_HOST: "${MYSQL_HOST}"
      WORDPRESS_DB_USER: "${WP_DBUSER}"
      WORDPRESS_DB_PASSWORD: "${WP_DBPASSWORD}"
      WORDPRESS_DB_NAME: "${WP_DBNAME}"
    volumes:
    - ./data:/var/www/html
    restart: unless-stopped
networks:
  default:
    name: $projectname
